---
# Установка Python 3, если не установлен (CentOS 7)
- name: Bootstrap Python if missing
  hosts: nexus
  gather_facts: false
  become: true
  tasks:
    - name: Ensure python3 is installed (for CentOS 7)
      raw: |
        yum install -y python3 || true
      changed_when: false

# Установка и настройка Nexus
- name: Get Nexus installed
  hosts: nexus
  become: true

  pre_tasks:
    - name: Create Nexus group
      group:
        name: "{{ nexus_user_group }}"
        state: present

    - name: Create Nexus user
      user:
        name: "{{ nexus_user_name }}"
        group: "{{ nexus_user_group }}"
        shell: /bin/bash
        create_home: yes

    - name: Install Java 8 (CentOS 7)
      yum:
        name:
          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
        state: present

  tasks:
    - name: Create Nexus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ nexus_user_name }}"
        group: "{{ nexus_user_group }}"
        mode: '0755'
      loop:
        - "{{ nexus_directory_log }}"
        - "{{ nexus_directory_data }}"
        - "{{ nexus_directory_data }}/etc"
        - "{{ nexus_directory_package }}"
        - "{{ nexus_directory_tmp }}"

    - name: Download Nexus
      get_url:
        url: "{{ nexus_download_url }}/nexus-{{ nexus_version }}-unix.tar.gz"
        dest: "{{ nexus_directory_package }}/nexus-{{ nexus_version }}.tar.gz"
        mode: '0644'

    - name: Extract Nexus
      unarchive:
        src: "{{ nexus_directory_package }}/nexus-{{ nexus_version }}.tar.gz"
        dest: "{{ nexus_directory_package }}"
        remote_src: yes
        creates: "{{ nexus_directory_package }}/nexus-{{ nexus_version }}"

    - name: Set permissions on extracted Nexus
      file:
        path: "{{ nexus_directory_package }}/nexus-{{ nexus_version }}"
        state: directory
        recurse: yes
        owner: "{{ nexus_user_name }}"
        group: "{{ nexus_user_group }}"

    - name: Create symlink to Nexus directory
      file:
        src: "{{ nexus_directory_package }}/nexus-{{ nexus_version }}"
        dest: "{{ nexus_directory_home }}"
        state: link
        owner: "{{ nexus_user_name }}"
        group: "{{ nexus_user_group }}"

    - name: Add NEXUS_HOME to .bashrc
      lineinfile:
        path: "/home/{{ nexus_user_name }}/.bashrc"
        line: "export NEXUS_HOME={{ nexus_directory_home }}"
        create: yes
        insertafter: EOF
        owner: "{{ nexus_user_name }}"
        group: "{{ nexus_user_group }}"

    - name: Set run_as_user in nexus.rc
      lineinfile:
        path: "{{ nexus_directory_home }}/bin/nexus.rc"
        line: 'run_as_user="{{ nexus_user_name }}"'
        create: yes
        owner: "{{ nexus_user_name }}"
        group: "{{ nexus_user_group }}"

    - name: Raise nofile limit for Nexus user
      pam_limits:
        domain: "{{ nexus_user_name }}"
        limit_type: "-"
        limit_item: nofile
        value: "{{ nexus_ulimit }}"

    - name: Create Nexus systemd service
      copy:
        dest: /etc/systemd/system/nexus.service
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          LimitNOFILE=65536
          User={{ nexus_user_name }}
          Group={{ nexus_user_group }}
          ExecStart={{ nexus_directory_home }}/bin/nexus start
          ExecStop={{ nexus_directory_home }}/bin/nexus stop
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd and enable/start Nexus
      systemd:
        daemon_reload: yes
        name: nexus
        enabled: yes
        state: started

    - name: Wait for Nexus port if started
      wait_for:
        port: "{{ nexus_port }}"
        state: started
        timeout: "{{ nexus_port_check_timeout }}"
      when: nexus_service_start_on_boot | default(true)
